print('====== DESAFIO 04 ======')
n = input('Digite qualquer coisa: ')
print('O tipo primitivo do valor é',type(n))
print('É somente espaços?',n.isspace())
print('É letra?',n.isalpha())
print('É letra maiúscula?',n.isupper())
print('É letra minúscula?',n.islower())
print('É capitalizada?',n.istitle())
print('É alfanumérico?',n.isalnum())
print('É número?',n.isnumeric())